sudo: required
services:
  - docker

before_install:
  - docker build -t muntianparaschiva/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run muntianparaschiva/react-test npm test -- --coverage

after_success:
  - docker build -t muntianparaschiva/multi-client ./client
  - docker build -t muntianparaschiva/multi-nginx ./nginx
  - docker build -t muntianparaschiva/multi-server ./server
  - docker build -t muntianparaschiva/multi-worker ./worker
  #first we should to login in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "DOCKER_ID" --password-stdin
  #take those images and push them to docker hub
  - docker push  muntianparaschiva/multi-client
  - docker push  muntianparaschiva/multi-nginx
  - docker push  muntianparaschiva/multi-server
  - docker push  muntianparaschiva/multi-worker
  